### PR TITLE
Initial config

### PR DESCRIPTION
**Pull request by triorbonk**

### CODE REVIEW

**Comment by triorbonk** [comment]
done

**Comment by triorbonk** [comment]
done

**Comment by triorbonk** [comment]
done

**Comment by triorbonk** [comment]
done

**Comment by triorbonk** [comment]
done

**Comment by triorbonk** [comment]
done

**Comment by triorbonk** [comment]
cone

**Comment by triorbonk** [comment]
done

**Comment by michaelusner** [comment]
You closed your PR - I'd be happy to merge it if you want.  I appreciate the contributions - especially the Prometheus exporter.  Sorry it took me a while to notice it - please resubmit if you want.

**Comment by triorbonk** [comment]
My apologies, I am not up on GitHub yet.  You are welcome to the code.  Ultimately I am working on an integration out to MQTT Mosquitto which I will post when I get it completed. 

Eric

**Comment by triorbonk** [comment]
Reopen for Michael.

**Review by michaelusner — APPROVED** [review]

**Comment by michaelusner** [comment]
Merged - thanks for the submission.  My first merged PR :)

**Pull request merged**
